### ISSUE TITLE
Use remote interpolation matrices

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-regrid#2]
### Is your feature request related to a problem? Please describe.

The task is to generate the matrices for a large number of possible input and output gridspecs (global grids only). 

As for the location of the matrices, they should be stored on the ECMWF download server and earthkit-regrid should be able to download them on demand.

### Organisation

ECMWF

**Comment by tlmquintino** [comment]
@sandorkertesz I dont think we should store any grids in the repo. This will create assimetries and differences of behaviour not to mention make the repo be heavier than necessary.

**Comment by sandorkertesz** [comment]
@tlmquintino I updated the description to reflect this.
